### ISSUE TITLE
Unable to open new warp [Error] Connection error: dial tcp 35.162.152.151:4242: getsockopt: connection refused

### ISSUE THREAD

**Issue by DEDS3C** [spolu/warp#22]
Hey, whenever i try to open an new warp / connection it, warp says it opened but then it sayts connection refused.

**Comment by ipfaffy** [comment]
Same here:

`[Error] Connection to warpd failed: dial tcp 35.162.152.151:4242: getsockopt: connection refused.`

What is this connecting to? is it porrible to run our own "warp server" to run this for a company, etc?

**Comment by DEDS3C** [comment]
pretty sure you can,

**Comment by manfredlift** [comment]
I have the same issue

**Comment by thoellrich** [comment]
Looks like you can build warpd, which is part of the package and set the env-var `WARPD_ADDRESS` to point at it before running `warp open`.

**Comment by spolu** [comment]
As @thoellrich said, it is possible to run your own `warpd` instance and override the default address with env variable `WARPD_ADDRESS` 👍

**Comment by spolu** [comment]
I just realized the default warpd had crashed. It is now back up and running!

**Comment by spolu** [comment]
Sorry for that!
