### ISSUE TITLE
Warp server down?

### ISSUE THREAD

**Issue by camflan** [spolu/warp#24]
It appears that the default warpd is down

```
❯: warp open hello-world-yo
Opened warp: hello-world-yo

[Error] Connection error: dial tcp 35.162.152.151:4242: getsockopt: connection refused
```

**Comment by spolu** [comment]
@camflan sorry! just restarted it!

**Comment by spolu** [comment]
I will look in what is causing it to crash

**Comment by spolu** [comment]
Fixed by https://github.com/spolu/warp/commit/728259c20eaa38c58fd2384359e47fa4b0add962

**Comment by camflan** [comment]
fantastic, thank you!
