### ISSUE TITLE
Error for warp open

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [spolu/warp#27]
warp cannot work now (9/7/2017), when I type warp open , the terminal shows:
[Error] Connection error: x509: certificate has expired or is not yet valid

but what happend? there is no document mention it.

**Comment by l2dy** [comment]
The default server's certificate expired on August 21th.

https://github.com/spolu/warp/blob/v0.0.3/protocol.go#L13
https://warp.link:4242/

**Comment by hh-in-zhuzhou** [comment]
@l2dy will this serve’s certificate be updated recently？thanx for your apply.

**Comment by l2dy** [comment]
That's not my server and I have no control over it. You can run your own `wrapd` server though.

With [Go](https://golang.org/) and Git installed, you can build the server with
`go get -u github.com/spolu/warp/daemon/cmd/warpd`.

**Comment by hh-in-zhuzhou** [comment]
@l2dy thank you very much！

**Comment by ghost** [comment]
Please tell me how to set the server...I used the command but I can't get `warp open` still @hh-in-zhuzhou

**Comment by hh-in-zhuzhou** [comment]
font{
        line-height: 1.5;
    }


    
sorry I have not made it OK too



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年10月24日 16:00，FredZhang<notifications@github.com> 写道： 


Please tell me how to set the server...I used the command but I can't get warp open still
