### ISSUE TITLE
Add a more explicit message for in-warp commands failing because of ENV missing

### ISSUE THREAD

**Issue by spolu** [spolu/warp#5]
Explicitly mention something along the lines:
```
Warp uses ENV variable to detect that it's running from within a warp. 
If you connected to a pre-existing tmux or a screen from a warp, these 
ENV variables won't be set. If you warp is named *goofy-dev*, you can 
fix this with `export __WARP=goofy-dev`.
```

Stop relying on `__WARP_UNIX_SOCKET` and rely on `__WARP` only

**Comment by suedadam** [comment]
Curious to see if I can help, could you elaborate on the purpose for the __WARP_UNIX_SOCKET and __WARP?

**Comment by suedadam** [comment]
Nevermind the source code is pretty easy to read but I am curious about one thing, are you using EnvWarp (__WARP) for anything other than making it easier for users to read (in verbosity)?

**Comment by spolu** [comment]
@suedadam hey! up until now we weren't using it. But that PR: https://github.com/spolu/warp/pull/8 makes use of it instead of `__WARP_UNIX_SOCKET`, so that we can have an actionable error message.

**Comment by spolu** [comment]
Would love to have your feedback on the new error message:
```
bash-3.2$ __WARP="" go run client/cmd/warp/main.go state

`warp` uses the environment variable `__WARP` to detect that it is running from
inside a warp (for in-warp commands). `__WARP` not being currently set, it
indicates that you are not executing this from inside a warp.

Expert mode: if you connected to a pre-existing tmux or screen session from
your current warp, `__WARP` will not be propagated automatically. You can fix
this by setting `__WARP` to the ID of your warp in your current environment.

[Error] This command is only available from inside a warp.
bash-3.2$
```

**Comment by suedadam** [comment]
@spolu That error message seems fine, I'd just give an example like you did in the first one (`export __WARP=goofy-dev`). This whole thread does spark my curiosity of if it is possible to preserve the warp ID through environment switching (programs like Tmux/Screen, etc.). Maybe there's a method of fetching/setting that is more reliable through swaps like this other than OS environment variables? If you're not sure then I can see about doing some research into it tonight to see what I can find!

**Comment by spolu** [comment]
@suedadam That would be awesome! I thought about it but couldn't find anything obvious. All yours!

Concerning the example, I'm worried that people with no clue will just copy the example and confuse themselves even more?

**Comment by suedadam** [comment]
@spolu I just read over the code and I think I completely reversed my understanding of the environment variable (Guess I'm a bit too tired for this tonight). 
The environment variable is simply being used to note the path for the sock file, correct? In that case it doesn't matter if a user outside of the warp is able to read it so couldn't we just make a temporary file storing the warp ID and have them access that? (Though that'd make the limitation of one warp session per computer/temp file).

@Example, Yeah you're right, but maybe something along the lines of making it obvious would help. Something like "Run `export __WARP=<ID>`"

**Comment by spolu** [comment]
Preserving even through re-attachment? I think we can create a wiki page and link it from the message?

Re example, fair. I'll update 👍🏻

**Comment by suedadam** [comment]
@spolu haha sorry I edited my response a few times, can you take a look at the latest edit? 
Simplified version of it: Can't we create a temporary file and store the value in there? We could then fetch the value of it when needed rather than through an environment variable.

**Comment by spolu** [comment]
@suedadam but how do you retrieve that file if there are multiple warp running?

**Comment by spolu** [comment]
Ah I see that you got already the one warp per user/machine. I think it's a bit too much of a limitation compared to what we're trying to protect against. wdyt?

**Comment by spolu** [comment]
I tweaked the error message to add an example command.

@suedadam do you want to document the way to propagate the __WARP env variable that you found for tmux and other situation in a wiki page?
