### ISSUE TITLE
Return error when connecting to a warp from itself

### ISSUE THREAD

**Issue by johnlukeG** [spolu/warp#7]
Hey! I'm trying to play around with warp to maybe see if I can use it for dev chat rather than slack. For some reason, anytime that I try to open a warp, it just hangs. I'm not sure if I'm just using it wrong or if it's a bug. It says connected, but I can't type anything or kill the process.
<img width="497" alt="screen shot 2017-04-26 at 10 29 54 am" src="https://cloud.githubusercontent.com/assets/10673175/25439762/5d0f1348-2a6b-11e7-8522-91325e41afcd.png">

I'm having the same behavior in zshell and bash. I've tried uninstalling go and warp and reinstalling.

go version `go1.8.1 darwin/amd64`.
OS: `macOS Sierra 10.12.4`

**Comment by spolu** [comment]
Ah! You're connecting to the warp from the warp itself. You just need `warp open` here.

The reason why it hangs is that the warp disable writes altogether from clients if no external client is authorized to write.

I will add a well explained error message when someone attempts to connect to the warp from inside the warp.

Thanks for the report!

**Comment by spolu** [comment]
In other words `open` opens the warp but also connects you to it.

**Comment by spolu** [comment]
I will also add a note in the README usage.

**Comment by johnlukeG** [comment]
Oh wow, I feel dumb 😅 . Thank you for the quick response!

**Comment by spolu** [comment]
@lukegarofalo no prob! this is very useful feedback. Working on a PR 👍
